apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240505225433.0.0+build.6aff574
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240505225433.0.0+build.6aff574
  releaseNotes: |
    Release v20240505225433.0.0+build.6aff574 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-05-05-2024-17-32-57-035029499/where-for-dinner-search-my-apps-bundle@sha256:536f341e09523ee53110b5ea65677654f7165c854051944f1d6ae249c4830d15
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

