apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240505225134.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240505225134.0.0+build.6aff574
  releaseNotes: |
    Release v20240505225134.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-05-05-2024-17-32-57-035029499/where-for-dinner-my-apps-bundle@sha256:3827321399325190171c57ac47e8dd23cf7bc41b23b59249ab76c71f4d5a06f4
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

